Add testing GitHub action (fixes #2)
SeisoLLC/zeek-kafka pull request #9
Opened 2021-01-06 14:43 UTC by JonZeolla

# Summary of the contribution
This updates `make test` to run our e2e tests, and adds a github action which runs `make test` on PRs to `main`.

This builds on the GitHub actions introduced in #1

## Testing
1. Run `make test` locally
2. Observer the github actions output from this PR.

## Checklist
- [X] Confirm that any associated issues are indicated in the pull request title
- [X] Rebase your PR against the latest commit within the target branch
- [X] Include steps to verify and test the intended change
- [X] Write or update unit tests and/or integration tests to verify your changes
- [X] Verify the basic functionality of the plugin by building and running locally via the [end to end testing script](https://github.com/SeisoLLC/zeek-kafka/blob/main/docker/run_end_to_end.sh)
- [X] Indicate whether or not this is a breaking change
- [X] Ensure that any new dependencies are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)

2021-01-07 12:17 UTC, ottobackwards commented
you want to rebase on main and force push this?

2021-01-07 13:55 UTC, JonZeolla commented
@ottobackwards good to go, pending CI

2021-01-07 14:17 UTC, ottobackwards requested changes

2021-01-07 14:17 UTC, ottobackwards commented on .github/workflows/ci.yml
>          run: make lint
I think we are going to want to cache the docker builds
https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei

2021-01-07 14:47 UTC, JonZeolla commented
CI failed because http://downloads.digitalcorpora.org/corpora/network-packet-dumps/2008-nitroba/nitroba.pcap is serving 500s

2021-01-07 16:10 UTC, JonZeolla commented
It looks like the 500 should have been a 404; they just moved the file.

2021-01-08 23:12 UTC, JonZeolla commented
@ottobackwards ready to go

2021-01-09 04:36 UTC, ottobackwards approved these changes

2021-01-09 04:36 UTC, merged